[api]
host = "0.0.0.0"
port = "3000"
documentation = "http://localhost:3000/swagger/index.html"

[mysql]
host = "localhost"
port = "3306"
user = "root"
password = "p34c3m4k3r"
database = "frete_rapido"
