[api]
host = "0.0.0.0"
port = "8080"
documentation = "http://localhost:8080/swagger/index.html"

[mysql]
host = "localhost"
port = "3307"
user = "freterapido"
password = "root"
database = "frete_rapido"
